"use client";
import React, { useState } from "react";
import { Shield, Plus, Pencil, Trash2, RefreshCw, Search } from 'lucide-react';
import { useApiData, apiCreate, apiUpdate, apiDelete } from '@/hooks/useApiData';

interface Record { id: string; passportNumber?: string; fullName?: string; nationality?: string; status?: string; expiryDate?: string; createdAt: string; }
export default function Page() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<Record | null>(null);
  const [form, setForm] = useState({ passportNumber: '', fullName: '', nationality: '', status: '', expiryDate: '' });
  const { records, total, totalPages, isLoading, error, mutate } = useApiData<Record>('/api/passports', { page, pageSize: 20, search: search || undefined });
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); try { if (editing) await apiUpdate('/api/passports', { id: editing.id, ...form }); else await apiCreate('/api/passports', form); setShowForm(false); setEditing(null); setForm({ passportNumber: '', fullName: '', nationality: '', status: '', expiryDate: '' }); mutate(); } catch (err: any) { alert(err.message); } };
  const handleDelete = async (id: string) => { if (!confirm('تأكيد الحذف؟')) return; try { await apiDelete('/api/passports', id); mutate(); } catch (err: any) { alert(err.message); } };
  return (
    <div className="min-h-screen bg-background p-4 md:p-6 space-y-4" dir="rtl">
      <div className="bg-card p-4 md:p-6 rounded-xl border border-border flex flex-col sm:flex-row justify-between gap-3">
        <div className="flex items-center gap-3"><Shield className="h-6 w-6 text-primary" /><div><h1 className="text-lg font-bold">إدارة الجوازات والهجرة</h1><p className="text-xs text-muted-foreground">سجل الجوازات ووثائق السفر</p></div></div>
        <div className="flex items-center gap-2"><div className="relative"><Search className="absolute right-2 top-2 h-4 w-4 text-muted-foreground" /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="بحث..." className="pl-3 pr-8 py-1.5 text-xs rounded-lg border border-border bg-background w-48" /></div><button onClick={mutate} className="p-2 rounded-lg border border-border hover:bg-muted"><RefreshCw className="h-4 w-4" /></button><button onClick={() => { setEditing(null); setForm({ passportNumber: '', fullName: '', nationality: '', status: '', expiryDate: '' }); setShowForm(true); }} className="flex items-center gap-1 px-3 py-1.5 text-xs rounded-lg bg-primary text-primary-foreground"><Plus className="h-3 w-3" />إضافة</button></div>
      </div>
      {showForm && (<div className="bg-card p-4 rounded-xl border border-border"><form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-3 gap-3"><input required value={form.passportNumber} onChange={e => setForm({...form, passportNumber: e.target.value})} placeholder="رقم الجواز" className="px-3 py-2 text-xs rounded-lg border border-border bg-background" /><input value={form.fullName} onChange={e => setForm({...form, fullName: e.target.value})} placeholder="الاسم الكامل" className="px-3 py-2 text-xs rounded-lg border border-border bg-background" /><input value={form.nationality} onChange={e => setForm({...form, nationality: e.target.value})} placeholder="الجنسية" className="px-3 py-2 text-xs rounded-lg border border-border bg-background" /><input value={form.status} onChange={e => setForm({...form, status: e.target.value})} placeholder="الحالة" className="px-3 py-2 text-xs rounded-lg border border-border bg-background" /><input value={form.expiryDate} onChange={e => setForm({...form, expiryDate: e.target.value})} type="date" placeholder="تاريخ الانتهاء" className="px-3 py-2 text-xs rounded-lg border border-border bg-background" /><div className="flex gap-2"><button type="submit" className="px-4 py-2 text-xs rounded-lg bg-primary text-primary-foreground">{editing ? 'تحديث' : 'حفظ'}</button><button type="button" onClick={() => { setShowForm(false); setEditing(null); }} className="px-4 py-2 text-xs rounded-lg border border-border">إلغاء</button></div></form></div>)}
      {error && <div className="bg-destructive/10 text-destructive p-3 rounded-lg text-xs">{error}</div>}
      <div className="bg-card rounded-xl border border-border overflow-x-auto"><table className="w-full text-xs"><thead className="bg-muted/50 border-b border-border"><tr><th className="p-3 text-right">رقم الجواز</th><th className="p-3 text-right">الاسم</th><th className="p-3 text-right">الجنسية</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">الانتهاء</th><th className="p-3 text-right">إجراءات</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={6} className="p-6 text-center"><RefreshCw className="h-4 w-4 animate-spin inline-block" /> جاري التحميل...</td></tr> : records.length === 0 ? <tr><td colSpan={6} className="p-6 text-center text-muted-foreground">لا توجد سجلات</td></tr> : records.map(r => (<tr key={r.id} className="border-b border-border hover:bg-muted/30"><td className="p-3 font-mono font-medium">{r.passportNumber || r.id}</td><td className="p-3">{r.fullName || '-'}</td><td className="p-3">{r.nationality || '-'}</td><td className="p-3">{r.status || '-'}</td><td className="p-3 text-muted-foreground">{r.expiryDate ? new Date(r.expiryDate).toLocaleDateString('ar-YE') : '-'}</td><td className="p-3"><div className="flex gap-1"><button onClick={() => { setEditing(r); setForm({ passportNumber: r.passportNumber || '', fullName: r.fullName || '', nationality: r.nationality || '', status: r.status || '', expiryDate: r.expiryDate || '' }); setShowForm(true); }} className="p-1.5 rounded hover:bg-muted"><Pencil className="h-3 w-3" /></button><button onClick={() => handleDelete(r.id)} className="p-1.5 rounded hover:bg-destructive/20 text-destructive"><Trash2 className="h-3 w-3" /></button></div></td></tr>))}</tbody></table>{totalPages > 1 && (<div className="p-3 flex items-center justify-between border-t border-border text-xs"><span>{total} سجل</span><div className="flex gap-1">{Array.from({ length: totalPages }, (_, i) => (<button key={i} onClick={() => setPage(i + 1)} className={`px-2 py-1 rounded ${page === i + 1 ? 'bg-primary text-primary-foreground' : 'hover:bg-muted'}`}>{i + 1}</button>))}</div></div>)}</div>
    </div>
  );
}