"use client";
import React, { useState } from "react";
import { Shield, Plus, Pencil, Trash2, RefreshCw, Search } from 'lucide-react';
import { useApiData, apiCreate, apiUpdate, apiDelete } from '@/hooks/useApiData';

interface Record { id: string; name: string; code?: string; governorateId?: string; governorateName?: string; }
export default function Page() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<Record | null>(null);
  const [form, setForm] = useState({ name: '', code: '', governorateId: '', governorateName: '' });
  const { records, total, totalPages, isLoading, error, mutate } = useApiData<Record>('/api/districts', { page, pageSize: 20, search: search || undefined });
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); try { if (editing) await apiUpdate('/api/districts', { id: editing.id, ...form }); else await apiCreate('/api/districts', form); setShowForm(false); setEditing(null); setForm({ name: '', code: '', governorateId: '', governorateName: '' }); mutate(); } catch (err: any) { alert(err.message); } };
  const handleDelete = async (id: string) => { if (!confirm('تأكيد الحذف؟')) return; try { await apiDelete('/api/districts', id); mutate(); } catch (err: any) { alert(err.message); } };
  const openEdit = (r: Record) => { setEditing(r); setForm({ name: r.name, code: r.code || '', governorateId: r.governorateId || '', governorateName: r.governorateName || '' }); setShowForm(true); };
  return (
    <div className="min-h-screen bg-background p-4 md:p-6 space-y-4" dir="rtl">
      <div className="bg-card p-4 md:p-6 rounded-xl border border-border flex flex-col sm:flex-row justify-between gap-3">
        <div className="flex items-center gap-3"><Shield className="h-6 w-6 text-primary" /><div><h1 className="text-lg font-bold">إدارة المديريات</h1><p className="text-xs text-muted-foreground">سجل المديريات والمناطق الإدارية</p></div></div>
        <div className="flex items-center gap-2"><div className="relative"><Search className="absolute right-2 top-2 h-4 w-4 text-muted-foreground" /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="بحث..." className="pl-3 pr-8 py-1.5 text-xs rounded-lg border border-border bg-background w-48" /></div><button onClick={mutate} className="p-2 rounded-lg border border-border hover:bg-muted"><RefreshCw className="h-4 w-4" /></button><button onClick={() => { setEditing(null); setForm({ name: '', code: '', governorateId: '', governorateName: '' }); setShowForm(true); }} className="flex items-center gap-1 px-3 py-1.5 text-xs rounded-lg bg-primary text-primary-foreground"><Plus className="h-3 w-3" />إضافة</button></div>
      </div>
      {showForm && (<div className="bg-card p-4 rounded-xl border border-border"><form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-3"><input required value={form.name} onChange={e => setForm({...form, name: e.target.value})} placeholder="اسم المديرية" className="px-3 py-2 text-xs rounded-lg border border-border bg-background" /><input value={form.code} onChange={e => setForm({...form, code: e.target.value})} placeholder="الرمز" className="px-3 py-2 text-xs rounded-lg border border-border bg-background" /><input value={form.governorateName} onChange={e => setForm({...form, governorateName: e.target.value})} placeholder="المحافظة" className="px-3 py-2 text-xs rounded-lg border border-border bg-background" /><div className="flex gap-2"><button type="submit" className="px-4 py-2 text-xs rounded-lg bg-primary text-primary-foreground">{editing ? 'تحديث' : 'حفظ'}</button><button type="button" onClick={() => { setShowForm(false); setEditing(null); }} className="px-4 py-2 text-xs rounded-lg border border-border">إلغاء</button></div></form></div>)}
      {error && <div className="bg-destructive/10 text-destructive p-3 rounded-lg text-xs">{error}</div>}
      <div className="bg-card rounded-xl border border-border overflow-x-auto"><table className="w-full text-xs"><thead className="bg-muted/50 border-b border-border"><tr><th className="p-3 text-right">الاسم</th><th className="p-3 text-right">الرمز</th><th className="p-3 text-right">المحافظة</th><th className="p-3 text-right">الإجراءات</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={4} className="p-6 text-center"><RefreshCw className="h-4 w-4 animate-spin inline-block" /> جاري التحميل...</td></tr> : records.length === 0 ? <tr><td colSpan={4} className="p-6 text-center text-muted-foreground">لا توجد سجلات</td></tr> : records.map(r => (<tr key={r.id} className="border-b border-border hover:bg-muted/30"><td className="p-3 font-medium">{r.name}</td><td className="p-3 font-mono">{r.code || '-'}</td><td className="p-3">{r.governorateName || '-'}</td><td className="p-3"><div className="flex gap-1"><button onClick={() => openEdit(r)} className="p-1.5 rounded hover:bg-muted"><Pencil className="h-3 w-3" /></button><button onClick={() => handleDelete(r.id)} className="p-1.5 rounded hover:bg-destructive/20 text-destructive"><Trash2 className="h-3 w-3" /></button></div></td></tr>))}</tbody></table>{totalPages > 1 && (<div className="p-3 flex items-center justify-between border-t border-border text-xs"><span>{total} سجل</span><div className="flex gap-1">{Array.from({ length: totalPages }, (_, i) => (<button key={i} onClick={() => setPage(i + 1)} className={`px-2 py-1 rounded ${page === i + 1 ? 'bg-primary text-primary-foreground' : 'hover:bg-muted'}`}>{i + 1}</button>))}</div></div>)}</div>
    </div>
  );
}